<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-BPQODCE" failures="1" tests="1" name="PositiveTest" time="8.118" errors="0" timestamp="2024-03-19T23:04:19 CET">
  <testcase classname="test.java.com.loginpagestest.PositiveLoginTests" name="logInTest" time="8.073">
    <failure type="java.lang.AssertionError" message="expected [http://the-internet.herokuapp.com/secure] but found [https://the-internet.herokuapp.com/secure]">
      <![CDATA[java.lang.AssertionError: expected [http://the-internet.herokuapp.com/secure] but found [https://the-internet.herokuapp.com/secure]
at test.java.com.loginpagestest.PositiveLoginTests.logInTest(PositiveLoginTests.java:46)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- logInTest -->
</testsuite> <!-- PositiveTest -->
